# Generated by Django 6.0.1 on 2026-01-30 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='This will be the URL: skandage.com/agent/ryan-siow', unique=True)),
                ('title', models.CharField(default='Financial Consultant', max_length=100)),
                ('company', models.CharField(default='Great Eastern', max_length=100)),
                ('phone_number', models.CharField(help_text='Format: 6591234567 (No + sign)', max_length=20)),
                ('whatsapp_message', models.CharField(default='Hi, I saw your profile and would like to know more.', max_length=200)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='headshots/')),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Critical Illness Protection', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('review_text', models.TextField()),
                ('screenshot', models.ImageField(blank=True, help_text='Upload WhatsApp screenshot if available', null=True, upload_to='reviews/')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='core.agent')),
            ],
        ),
    ]
