# Generated by Django 6.0.1 on 2026-01-30 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agent_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. MDRT 2024, ChFC, Top Rookie', max_length=100)),
                ('issuer', models.CharField(help_text='e.g. Million Dollar Round Table, Prudential', max_length=100)),
                ('year', models.CharField(blank=True, help_text='Optional, e.g. 2023', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='core.agent')),
            ],
        ),
    ]
