# Generated by Django 6.0.1 on 2026-01-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='tagline',
            field=models.CharField(default='Here for you, always.', max_length=200),
        ),
    ]
