# Generated by Django 6.0.1 on 2026-02-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='can_upload_testimonials',
            field=models.BooleanField(default=False, help_text='If True, agent can add/upload testimonials freely. If False, button is hidden.'),
        ),
    ]
