# Generated by Django 6.0.1 on 2026-02-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agent_can_upload_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Check this to pin this review to the homepage'),
        ),
    ]
