# Generated by Django 6.0.1 on 2026-02-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_testimonial_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='theme',
            field=models.CharField(choices=[('luxe', 'Luxe Minimal (Stone & Amber)'), ('corporate', 'Corporate Blue (Navy & White)'), ('midnight', 'Midnight Neon (Dark & Cyan)')], default='luxe', max_length=20),
        ),
    ]
