# Generated by Django 6.0.1 on 2026-02-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_agent_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='layout',
            field=models.CharField(choices=[('classic', 'Classic Split (Image Left, Text Right)'), ('centered', 'Impact Center (Centered Text & Image)'), ('minimal', 'Minimalist (Text Only, No Hero Image)')], default='classic', max_length=20),
        ),
    ]
