# Generated by Django 6.0.1 on 2026-02-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_agent_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('bxs-shield', 'Protection / Shield'), ('bxs-heart', 'Life / Health'), ('bxs-briefcase', 'Retirement / Business'), ('bxs-bar-chart-alt-2', 'Investment / Growth'), ('bxs-graduation', 'Education / Planning'), ('bxs-home-heart', 'Mortgage / Housing'), ('bxs-plane-alt', 'Travel / Lifestyle'), ('bxs-badge-dollar', 'Wealth / Tax')], default='bxs-shield', max_length=50),
        ),
    ]
