# Generated by Django 6.0.1 on 2026-02-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='facebook',
            field=models.URLField(blank=True, help_text='Full URL (e.g. https://facebook.com/name)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='instagram',
            field=models.URLField(blank=True, help_text='Full URL (e.g. https://instagram.com/name)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Full URL (e.g. https://linkedin.com/in/name)'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='theme',
            field=models.CharField(choices=[('luxe', 'Luxe Minimal (Stone & Amber)'), ('corporate', 'Corporate Blue (Navy & White)'), ('midnight', 'Midnight Neon (Dark & Cyan)'), ('sunset', 'Sunset (Warm Orange & Cream)'), ('cotton', 'Cotton (Monochrome Black & White)'), ('glacier', 'Glacier (White & Icy Blue)'), ('blush', 'Blush (White & Rose Gold)')], default='luxe', max_length=20),
        ),
    ]
