# Generated by Django 6.0.1 on 2026-02-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_agent_facebook_agent_instagram_agent_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='disclaimer',
            field=models.TextField(default='The content on this website is strictly for information and educational purposes only and does not constitute financial advice. Investments are subject to market risks. Please consult a qualified financial consultant before making any decisions. Views expressed here are my own and do not necessarily reflect the official policy or position of my company.\n\nThis advertisement has not been reviewed by the Monetary Authority of Singapore.', help_text='This text appears in the footer of every page.'),
        ),
    ]
