# Generated by Django 6.0.1 on 2026-02-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_agent_disclaimer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='credential',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
