# Generated by Django 6.0.1 on 2026-02-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_credential_options_credential_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profile_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
