# Generated by Django 6.0.1 on 2026-02-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_agent_profile_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='title',
            field=models.CharField(blank=True, help_text="e.g. 'Built on Trust' or 'Great Service'", max_length=200),
        ),
    ]
