# Generated by Django 6.0.1 on 2026-02-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_testimonial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_published',
            field=models.BooleanField(default=True, help_text='If False, it will be hidden until approved.'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
