# Generated by Django 6.0.1 on 2026-02-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_reviewlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='custom_domain',
            field=models.CharField(blank=True, help_text="e.g. 'yq-partners.com'. If set, the agent will be accessible on this domain. They are ALWAYS accessible on skandage.com.", max_length=100, null=True),
        ),
    ]
