# Generated by Django 6.0.1 on 2026-02-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_agent_custom_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Uncheck this to disable the profile (404 error).'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='can_upload_testimonials',
            field=models.BooleanField(default=False, help_text='If True, agent can add/upload testimonials freely.'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='custom_domain',
            field=models.CharField(blank=True, help_text="e.g. 'yq-partners.com'. If set, agent loads on this domain.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='facebook',
            field=models.URLField(blank=True, help_text='Full URL'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='instagram',
            field=models.URLField(blank=True, help_text='Full URL'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Full URL'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='credential',
            name='issuer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='credential',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='credential',
            name='year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
