# Generated by Django 6.0.1 on 2026-02-13 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_agent_is_public_alter_agent_can_upload_testimonials_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='YQ Partners', max_length=100)),
                ('domain', models.CharField(help_text='e.g. yq-partners.com', max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agency/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='agency/favicons/')),
                ('primary_color', models.CharField(default='#2563EB', help_text='Hex code (e.g. #2563EB)', max_length=7)),
                ('secondary_color', models.CharField(default='#1E293B', help_text='Hex code (e.g. #1E293B)', max_length=7)),
                ('hero_headline', models.CharField(default='Securing Futures, Building Legacies.', max_length=200)),
                ('hero_subheadline', models.TextField(default='A collective of top-tier financial consultants dedicated to providing comprehensive wealth management.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='agency/hero/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='For the main floating chat button', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_site', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
