# Generated by Django 6.0.1 on 2026-02-13 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='favicon',
        ),
        migrations.AddField(
            model_name='agency',
            name='about_text',
            field=models.TextField(blank=True, default='We are a premier agency focused on...'),
        ),
        migrations.AddField(
            model_name='agency',
            name='values_text',
            field=models.TextField(blank=True, default='Integrity, Excellence, Compassion.'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='AgencyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='agency/gallery/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.agency')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc_name', models.CharField(max_length=100)),
                ('fc_role', models.CharField(default='Financial Consultant', max_length=100)),
                ('fc_photo', models.ImageField(blank=True, null=True, upload_to='agency/fc_reviews/')),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fc_reviews', to='core.agency')),
            ],
        ),
    ]
