# Generated by Django 6.0.1 on 2026-02-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_agency_favicon_agency_about_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='theme',
            field=models.CharField(choices=[('luxe', 'Luxe Minimal (Stone & Amber)'), ('corporate', 'Corporate Blue (Navy & White)'), ('midnight', 'Midnight Neon (Dark & Cyan)'), ('sunset', 'Sunset (Warm Orange & Cream)'), ('cotton', 'Cotton (Monochrome Black & White)'), ('glacier', 'Glacier (White & Icy Blue)'), ('blush', 'Blush (White & Rose Gold)'), ('midnight_rose', 'Midnight Rose (Obsidian & Soft Pink)')], default='luxe', max_length=20),
        ),
    ]
