# Generated by Django 6.0.1 on 2026-02-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_agent_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='page_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
