# Generated by Django 6.0.1 on 2026-03-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_agency_page_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='calendly_link',
            field=models.URLField(blank=True, help_text='e.g., https://calendly.com/your-username', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='theme',
            field=models.CharField(choices=[('luxe', 'Luxe Minimal (Stone & Amber)'), ('corporate', 'Corporate Blue (Navy & White)'), ('midnight', 'Midnight Neon (Dark & Cyan)'), ('midnight_rose', 'Midnight Rose (Black & Pink)'), ('executive', 'Executive Gold (Black & Gold)'), ('vogue', 'Vogue Editorial (Alabaster & Charcoal)'), ('sterling', 'Sterling Fintech (Slate & Blue)'), ('emerald', 'Private Client (Deep Green)'), ('obsidian', 'Obsidian (Black & White)'), ('royal', 'Royal Navy (Deep Blue & Silver)')], default='luxe', max_length=20),
        ),
    ]
