# Generated by Django 6.0.1 on 2026-03-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_newsletter_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional PDF attachment', null=True, upload_to='newsletters/attachments/'),
        ),
    ]
