# Generated by Django 6.0.1 on 2026-03-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_newsletter_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='html_file',
            field=models.FileField(blank=True, help_text='Upload a custom HTML template', null=True, upload_to='newsletters/html/'),
        ),
    ]
