# Generated by Django 6.0.1 on 2026-03-01 16:14

import hashlib
from cryptography.fernet import Fernet
from django.conf import settings
from django.db import migrations, models


def migrate_emails_forward(apps, schema_editor):
    """Hash and encrypt existing plain-text emails."""
    Subscriber = apps.get_model('core', 'Subscriber')
    f = Fernet(settings.ENCRYPTION_KEY)
    for sub in Subscriber.objects.all():
        clean_email = sub.email.lower().strip()
        sub.email_hash = hashlib.sha256(clean_email.encode('utf-8')).hexdigest()
        sub.encrypted_email = f.encrypt(clean_email.encode('utf-8'))
        sub.save(update_fields=['email_hash', 'encrypted_email'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_newsletter_html_file'),
    ]

    operations = [
        # Step 1: Add the new fields with defaults (so existing rows aren't broken)
        migrations.AddField(
            model_name='subscriber',
            name='email_hash',
            field=models.CharField(default='temp_hash', help_text='Used for duplicate checking', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='encrypted_email',
            field=models.BinaryField(default=b'temp_encrypted', help_text='The securely vaulted email'),
            preserve_default=False,
        ),
        # Step 2: Populate the new fields from existing plain-text email
        migrations.RunPython(migrate_emails_forward, migrations.RunPython.noop),
        # Step 3: Now that hashes are unique, add the constraint
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together={('agent', 'email_hash')},
        ),
        # Step 4: Remove the old plain-text email field
        migrations.RemoveField(
            model_name='subscriber',
            name='email',
        ),
    ]
