# Generated by Django 6.0.1 on 2026-03-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_subscriber_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='vcard_downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
