# Generated by Django 6.0.1 on 2026-03-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_agent_vcard_downloads'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Internal title (e.g., 'March 2026 Update')", max_length=200)),
                ('subject', models.CharField(help_text='The exact email subject line clients will see', max_length=200)),
                ('content', models.TextField(help_text='Paste your plain text or paragraph content here. Do not add HTML, the wrapper handles that.')),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
