# Generated by Django 6.0.1 on 2026-03-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_globalnewsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Stored natively for Celery cron job querying', null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='race',
            field=models.CharField(choices=[('C', 'Chinese'), ('M', 'Malay'), ('I', 'Indian'), ('O', 'Others')], default='O', max_length=1),
        ),
    ]
