# Generated by Django 6.0.1 on 2026-03-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_subscriber_date_of_birth_subscriber_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name (e.g., 'Professional Navy Blue')", max_length=100)),
                ('image', models.ImageField(help_text='The card design image', upload_to='card_templates/')),
                ('occasion', models.CharField(help_text="e.g., 'Lunar New Year', 'Deepavali', 'Birthday', 'Christmas'", max_length=100)),
                ('target_gender', models.CharField(choices=[('M', 'Males Only'), ('F', 'Females Only'), ('A', 'Any Gender')], default='A', max_length=1)),
                ('target_age_min', models.PositiveIntegerField(default=0, help_text='Minimum age (inclusive)')),
                ('target_age_max', models.PositiveIntegerField(default=120, help_text='Maximum age (inclusive)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['occasion', 'name'],
            },
        ),
    ]
