# Generated by Django 6.0.1 on 2026-03-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_cardtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='encrypted_email',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='source',
            field=models.CharField(default='manual', max_length=100),
        ),
    ]
