# Generated by Django 6.0.1 on 2026-03-04 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_subscriber_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtemplate',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_templates', to='core.agent'),
        ),
        migrations.AddField(
            model_name='cardtemplate',
            name='default_message',
            field=models.TextField(default='Wishing you joy and happiness on this special occasion!', help_text='Default message sent with this card design'),
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='image',
            field=models.ImageField(blank=True, help_text='The card design image (optional)', null=True, upload_to='card_templates/'),
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='occasion',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Lunar New Year', 'Lunar New Year'), ('Mid-Autumn Festival', 'Mid-Autumn Festival'), ('Deepavali', 'Deepavali'), ('Hari Raya Aidilfitri', 'Hari Raya Aidilfitri'), ('Hari Raya Haji', 'Hari Raya Haji'), ('Christmas', 'Christmas'), ('New Year', 'New Year'), ('Pongal', 'Pongal'), ('Other', 'Other')], help_text="e.g., 'Lunar New Year', 'Deepavali', 'Birthday', 'Christmas'", max_length=100),
        ),
    ]
