# Generated by Django 6.0.1 on 2026-03-04 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_cardtemplate_agent_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='automation_mode',
            field=models.CharField(choices=[('manual', 'Manual Approval'), ('auto', 'Fully Automated')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='agent',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Optional: Receive daily summaries here instead of your login email.', max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='CardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scheduled_date', models.DateField(help_text='The actual date of the birthday/festival')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_logs', to='core.agent')),
                ('card_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cardtemplate')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_logs', to='core.subscriber')),
            ],
            options={
                'ordering': ['-scheduled_date', 'subscriber__name'],
                'unique_together': {('subscriber', 'occasion', 'scheduled_date')},
            },
        ),
    ]
