# Generated by Django 6.0.1 on 2026-03-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_agent_automation_mode_agent_notification_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='tags',
            field=models.CharField(blank=True, help_text="Comma-separated tags (e.g. 'HNW, Retirement, Lunar New Year')", max_length=500),
        ),
    ]
