# Generated by Django 6.0.1 on 2026-03-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_subscriber_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardlog',
            options={'ordering': ['-scheduled_date']},
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='race',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='tags',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='birth_day',
            field=models.IntegerField(blank=True, help_text='Used for safe SQL birthday querying', null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='birth_month',
            field=models.IntegerField(blank=True, help_text='Used for safe SQL birthday querying', null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='encrypted_dob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='encrypted_gender',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='encrypted_name',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='encrypted_race',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='encrypted_tags',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='name_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='encrypted_email',
            field=models.BinaryField(default=b''),
        ),
    ]
