# Generated by Django 6.0.1 on 2026-03-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_cardlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='encrypted_address',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='encrypted_notes',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='encrypted_phone',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='lead_source',
            field=models.CharField(choices=[('referred', 'Referred'), ('cold', 'Cold'), ('others', 'Others')], default='others', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='next_review_date',
            field=models.DateField(blank=True, help_text='Calculated date for the next policy review', null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='pipeline_status',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('client', 'Client')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='encrypted_email',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='encrypted_gender',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='encrypted_name',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='encrypted_race',
            field=models.BinaryField(),
        ),
    ]
