# Generated by Django 6.0.1 on 2026-03-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_subscriber_encrypted_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='last_review_date',
            field=models.DateField(blank=True, help_text='Date of the most recent review — used to recalculate next review date', null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='review_freq_months',
            field=models.PositiveIntegerField(blank=True, help_text='Review interval in months (e.g. 6 or 12)', null=True),
        ),
    ]
