# Generated by Django 6.0.1 on 2026-03-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_subscriber_review_freq_and_last_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAgentOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text='Mobile / WhatsApp Number', max_length=20)),
                ('agency_name', models.CharField(default='AIAFA', help_text='Which agency are they joining under?', max_length=100)),
                ('job_title', models.CharField(default='Financial Consultant', max_length=100)),
                ('requested_subdomain', models.CharField(help_text="e.g. 'benedict' for benedict.aiafa.com.sg", max_length=100)),
                ('bio', models.TextField(blank=True, help_text="Agent's background story")),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='onboarding/headshots/')),
                ('credentials_upload', models.FileField(blank=True, help_text='PDF or Image of certifications', null=True, upload_to='onboarding/credentials/')),
                ('existing_website', models.URLField(blank=True, help_text='Link to scrape existing testimonials from', null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved & Account Created'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
