# Generated by Django 6.0.1 on 2026-03-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_pendingagentonboarding_requested_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bespoke_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores unique editable fields just for this agent'),
        ),
        migrations.AddField(
            model_name='agent',
            name='bespoke_template_name',
            field=models.CharField(blank=True, help_text="e.g., 'themes/karna_custom.html'", max_length=50),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_bespoke',
            field=models.BooleanField(default=False, help_text='True if client paid for a 1-of-1 custom design'),
        ),
    ]
