# Generated by Django 6.0.1 on 2026-03-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_agent_bespoke_data_agent_bespoke_template_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='video',
            field=models.FileField(blank=True, help_text='Upload MP4 or MOV files', null=True, upload_to='reviews/videos/'),
        ),
    ]
