# Generated by Django 6.0.1 on 2026-03-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_testimonial_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Used for instant lead notifications', max_length=50, null=True),
        ),
    ]
