# Generated by Django 6.0.1 on 2026-03-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='theme',
            field=models.CharField(choices=[('luxe', 'Luxe Minimal (Stone & Amber)'), ('corporate', 'Corporate Blue (Navy & White)'), ('midnight', 'Midnight Neon (Dark & Cyan)'), ('midnight_rose', 'Midnight Rose (Black & Pink)'), ('executive', 'Executive Gold (Black & Gold)'), ('vogue', 'Vogue Editorial (Alabaster & Charcoal)'), ('sterling', 'Sterling Fintech (Slate & Blue)'), ('emerald', 'Private Client (Deep Green)'), ('obsidian', 'Obsidian (Black & White)'), ('royal', 'Royal Navy (Deep Blue & Silver)'), ('midnight_spring', 'Royal Navy (Deep Blue & Silver)')], default='luxe', max_length=20),
        ),
    ]
