# Generated by Django 6.0.1 on 2026-03-12 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_agent_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='theme',
            field=models.CharField(choices=[('luxe', 'Luxe Minimal (Stone & Amber)'), ('corporate', 'Corporate Blue (Navy & White)'), ('midnight', 'Midnight Neon (Dark & Cyan)'), ('midnight_rose', 'Midnight Rose (Black & Pink)'), ('executive', 'Executive Gold (Black & Gold)'), ('vogue', 'Vogue Editorial (Alabaster & Charcoal)'), ('sterling', 'Sterling Fintech (Slate & Blue)'), ('emerald', 'Private Client (Deep Green)'), ('obsidian', 'Obsidian (Black & White)'), ('royal', 'Royal Navy (Deep Blue & Silver)')], default='luxe', max_length=20),
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_otp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
