# Generated by Django 6.0.1 on 2026-03-12 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_agent_theme_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VAULT_VIEWED', 'Viewed Entire Vault'), ('CLIENT_VIEWED', 'Viewed Single Client Details'), ('CLIENT_EXPORTED', 'Exported Vault to CSV'), ('CLIENT_DELETED', 'Deleted Client Record')], max_length=50)),
                ('target_info', models.CharField(help_text="e.g., 'Client: John Doe (ID: 4)' or 'Exported 150 clients'", max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.agent')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
