# Generated by Django 6.0.1 on 2026-03-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When the agent soft-deleted this record', null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_anonymized',
            field=models.BooleanField(default=False, help_text='True if PII was scrubbed after 7 years'),
        ),
    ]
