# Generated by Django 6.0.1 on 2026-03-12 13:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_subscriber_archived_at_subscriber_is_anonymized'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='is_subscribed',
            field=models.BooleanField(default=True, help_text='False if client opted out of bulk marketing/cards'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
