# Generated by Django 6.0.1 on 2026-03-12 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_subscriber_unsubscribe_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
