# Generated by Django 6.0.1 on 2026-03-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_subscriber_unsubscribe_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingagentonboarding',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
