# Generated by Django 6.0.1 on 2026-03-13 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_pendingagentonboarding_stripe_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_views', to='core.agent')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('agent', 'date')},
            },
        ),
    ]
