# Generated by Django 6.0.1 on 2026-03-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_passkeycredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='skip_passkey_prompt',
            field=models.BooleanField(default=False),
        ),
    ]
