"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-j#5(=%n-%0omvrmhjil65==^ph=c!v*6$grf!++dxn%)s1erka')

# SECURITY WARNING: don't run with debug turned on in production!
# We check if we are on Render by looking for the 'RENDER' environment variable
DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = ['.skandage.com', 'skandage-app.onrender.com', 'localhost', '127.0.0.1', '192.168.1.13', 'benedict.skandage.com', '.yq-partners.com', 'onboarding.skandage.test', 'karna.localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',       # Your App
    'storages',   # AWS S3 Library
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # WhiteNoise must be here
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
SITE_URL = 'https://skandage-app.onrender.com' if not DEBUG else 'http://127.0.0.1:8000'

# DATABASE CONFIG (Switch to Postgres on Server)
if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=600,
        conn_health_checks=True,
    )


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
#ENCRYPTION FOR EMAILS
ENCRYPTION_KEY = b'PKhR0eKUBNCRHxdl3ewdgFNwb6XsiC-cTBX7TMluMEY='
#EMAIL BACKEND
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.resend.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'resend'
EMAIL_HOST_PASSWORD = 're_P5vUN1Ae_7ixeBPH1YF8muB3R73J353za' # GET THIS FROM RESEND
DEFAULT_FROM_EMAIL = 'updates@skandage.com'

# ==========================================
# STATIC & MEDIA FILES (The Important Part)
# ==========================================

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Disable strict manifest so Tailwind V4 @imports don't crash collectstatic
WHITENOISE_MANIFEST_STRICT = False

# Login Redirects
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# AWS S3 SETTINGS (Only used if keys are present in Environment)
if 'AWS_ACCESS_KEY_ID' in os.environ:
    # AWS Config
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    
    # Quick CTO Note: If your AWS bucket is in Singapore, this should be 'ap-southeast-1'
    AWS_S3_REGION_NAME = 'ap-southeast-2' 
    
    AWS_S3_ADDRESSING_STYLE = "virtual"
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_S3_VERIFY = True

    # --- THE CLOUDFLARE CDN UPGRADE ---
    # This routes all media traffic through your edge network to kill egress costs.
    # If you prefer, you can also use os.environ.get('CDN_DOMAIN', 'cdn.skandage.com') here.
    AWS_S3_CUSTOM_DOMAIN = 'cdn.skandage.com'

    # STORAGE CONFIGURATION (Django 6.0+)
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    # LOCAL DEVELOPMENT FALLBACK (No AWS keys)
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }